apiVersion: v1
kind: Service
metadata:
  name: vpromq01
  labels:
    app: vpromq01
spec:
  selector:
    app: vpromq01
  ports:
  - name: amqp
    port: 5672
    targetPort: amqp
  - name: management
    port: 15672
    targetPort: management
  type: ClusterIP
